name: Array API CI
on:
  workflow_dispatch:
  # Temporary addition to execute workflow on pull requests, but only those
  # that modify this file
  pull_request:
    paths:
      - ".github/workflows/gpu-ci.yml"

jobs:
  tests:
    runs-on: GPU
    name: Run Array API unit tests
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install miniforge
        run: |
          curl -L -O "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
          bash Miniforge3-$(uname)-$(uname -m).sh -b -p "${HOME}/conda"
          source "${HOME}/conda/etc/profile.d/conda.sh"
          rm Miniforge3-$(uname)-$(uname -m).sh
      - name: Install dependencies
        run: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          # defines the get_dep and show_installed_libraries functions
          source build_tools/shared.sh
          conda activate base
          conda install -c conda-forge "$(get_dep conda-lock min)" -y
          conda-lock install --name sklearn build_tools/github/pylatest_conda_forge_mkl_array-api_linux-64_conda.lock
      - name: Install scikit-learn
        run: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          conda activate sklearn
          pip install --verbose --no-build-isolation --config-settings editable-verbose=true --editable .
      - name: Run array API tests
        run: |
          source "${HOME}/conda/etc/profile.d/conda.sh"
          conda activate sklearn
          pytest -k 'array_api'
