on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: GPU
    name: Run Array API unit tests
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          source $CONDA/bin/activate
          # defines the get_dep and show_installed_libraries functions
          source build_tools/shared.sh
          conda install -n base conda conda-libmamba-solver -y
          conda config --set solver libmamba
          conda install -c conda-forge "$(get_dep conda-lock min)" -y
          conda-lock install --name sklearn build_tools/azure/pylatest_conda_forge_mkl_linux-64_conda.lock

      - name: look around
        run: |
          source activate sklearn
          python --version
          nvidia-smi
