name: Array API CI
on:
  workflow_dispatch:
  # Temporary addition to execute workflow on pull requests, but only those
  # that modify this file
  pull_request:
    paths:
      - ".github/workflows/gpu-ci.yml"

jobs:
  tests:
    runs-on: GPU
    name: Run Array API unit tests
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: show env
        run: |
          env
      - name: quo vadis conda?
        run: |
          ls -hals /opt/miniconda
      - name: Install dependencies
        run: |
          # defines the get_dep and show_installed_libraries functions
          source build_tools/shared.sh
          # mamba solver is already installed and configured
          #conda install -n base conda conda-libmamba-solver -y
          #conda config --set solver libmamba
          sudo conda install -c conda-forge "$(get_dep conda-lock min)" -y
          sudo conda-lock install --name sklearn build_tools/azure/pylatest_conda_forge_mkl_linux-64_conda.lock

      - name: look around
        run: |
          conda activate sklearn
          python --version
          nvidia-smi
